name: 'Parse Warp Id'
description: 'Parses the Warp ID (e.g. ETH/base-eth) from the github comments'

inputs:
  body:
    description: 'The raw text of the Github Body'
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse Warp Id
      shell: bash
      env:
        BODY: ${{ inputs.body }}
      run: |
        regex="warp-route-deploy:[[:space:]]*([^[:space:]]+)"
        if [[ $BODY =~ $regex ]]; then
          WARP_ID="${BASH_REMATCH[1]}"
          echo "WARP_ID=$WARP_ID" >> "$GITHUB_ENV"
          echo "Warp Id parsed: $WARP_ID"
        else
          echo Could not parse warp Id
        fi
