name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read

jobs:
  say_hello:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, a new comment was added to a PR!!"
